const Map<String, List<String>> departamentosYmunicipios = {
  'Atlántida': [
    'La Ceiba',
    'El Porvenir',
    'Tela',
    'Jutiapa',
    'La Masica',
    'Arizona',
    'Esparta',
    'San Francisco',
  ],
  'Colón': [
    'Trujillo',
    'Balfate',
    'Iriona',
    'Limón',
    'Sabá',
    'Santa Fe',
    'Santa Rosa de Aguán',
    'Sonaguera',
    'Tocoa',
    'Bonito Oriental',
  ],
  'Comayagua': [
    'Comayagua',
    'Ajuterique',
    'El Rosario',
    'Esquías',
    'Humuya',
    'La Libertad',
    'Lamaní',
    'La Trinidad',
    'Lejamaní',
    'Meámbar',
    'Minas de Oro',
    'Ojos de Agua',
    'San Jerónimo',
    'San José de Comayagua',
    'San José del Potrero',
    'San Luis',
    'San Sebastián',
    'Siguatepeque',
    'Taulabé',
    'Villa de San Antonio',
  ],
  'Copán': [
    'Santa Rosa de Copán',
    'Cabañas',
    'Concepción',
    'Copán Ruinas',
    'Corquín',
    'Cucuyagua',
    'Dolores',
    'Dulce Nombre',
    'El Paraíso',
    'Florida',
    'La Jigua',
    'La Unión',
    'Nueva Arcadia',
    'San Agustín',
    'San Antonio',
    'San Jerónimo',
    'San José',
    'San Juan de Opoa',
    'San Nicolás',
    'San Pedro',
    'Santa Rita',
    'Trinidad de Copán',
    'Veracruz',
  ],
  'Cortés': [
    'San Pedro Sula',
    'Choloma',
    'La Lima',
    'Pimienta',
    'Potrerillos',
    'Puerto Cortés',
    'San Antonio de Cortés',
    'San Francisco de Yojoa',
    'San Manuel',
    'Santa Cruz de Yojoa',
    'Villanueva',
  ],
  'Choluteca': [
    'Choluteca',
    'Apacilagua',
    'Concepción de María',
    'Duyure',
    'El Corpus',
    'El Triunfo',
    'Marcovia',
    'Morolica',
    'Namasigüe',
    'Orocuina',
    'Pespire',
    'San Antonio de Flores',
    'San Isidro',
    'San José',
    'San Marcos de Colón',
    'Santa Ana de Yusguare',
  ],
  'El Paraíso': [
    'Yuscarán',
    'Alauca',
    'Danlí',
    'El Paraíso',
    'Guinope',
    'Jacaleapa',
    'Liure',
    'Morocelí',
    'Oropolí',
    'Potrerillos',
    'San Antonio de Flores',
    'San Lucas',
    'San Matías',
    'Soledad',
    'Teupasenti',
    'Texiguat',
    'Vado Ancho',
    'Yauyupe',
    'Trojes',
  ],
  'Francisco Morazán': [
    'Tegucigalpa',
    'Alubarén',
    'Cedros',
    'Curarén',
    'Distrito Central',
    'El Porvenir',
    'Guaimaca',
    'La Libertad',
    'La Venta',
    'Lepaterique',
    'Maraita',
    'Marale',
    'Nueva Armenia',
    'Ojojona',
    'Orica',
    'Reitoca',
    'Sabanagrande',
    'San Antonio de Oriente',
    'San Buenaventura',
    'San Ignacio',
    'San Juan de Flores',
    'San Miguelito',
    'Santa Ana',
    'Santa Lucía',
    'Talanga',
    'Tatumbla',
    'Valle de Ángeles',
    'Vallecillo',
    'Villa de San Francisco',
  ],
  'Gracias a Dios': [
    'Puerto Lempira',
    'Ahuas',
    'Brus Laguna',
    'Juan Francisco Bulnes',
    'Ramón Villeda Morales',
    'Wampusirpi',
  ],
  'Intibucá': [
    'La Esperanza',
    'Camasca',
    'Colomoncagua',
    'Concepción',
    'Dolores',
    'Intibucá',
    'Jesús de Otoro',
    'Magdalena',
    'Masaguara',
    'San Antonio',
    'San Isidro',
    'San Juan',
    'San Marcos de la Sierra',
    'San Miguelito',
    'Santa Lucía',
    'Yamaranguila',
  ],
  'Islas de la Bahía': [
    'Roatán',
    'Guanaja',
    'José Santos Guardiola',
    'Utila',
  ],
  'La Paz': [
    'La Paz',
    'Aguanqueterique',
    'Cabañas',
    'Cane',
    'Chinacla',
    'Guajiquiro',
    'Lauterique',
    'Marcala',
    'Mercedes de Oriente',
    'Opatoro',
    'San Antonio del Norte',
    'San José',
    'San Juan',
    'San Pedro de Tutule',
    'Santa Ana',
    'Santa Elena',
    'Santa María',
    'Santiago de Puringla',
    'Yarula',
  ],
  'Lempira': [
    'Gracias',
    'Belén',
    'Candelaria',
    'Cololaca',
    'Erandique',
    'Gualcince',
    'Guarita',
    'La Campa',
    'La Iguala',
    'Las Flores',
    'La Unión',
    'La Virtud',
    'Lepaera',
    'Mapulaca',
    'Piraera',
    'San Andrés',
    'San Francisco',
    'San Juan Guarita',
    'San Manuel Colohete',
    'San Marcos de Caiquín',
    'San Rafael',
    'San Sebastián',
    'Santa Cruz',
    'Talgua',
    'Tambla',
    'Tomalá',
    'Valladolid',
    'Virginia',
  ],
  'Ocotepeque': [
    'Ocotepeque',
    'Belén Gualcho',
    'Concepción',
    'Dolores Merendón',
  ]
};
